import type { Scenario } from '@/types/quiz'

export const SCENARIOS: Scenario[] = [
  // ============================================================
  // BATCH 1 — ROMANTIC CONFLICT (Scenarios 1–10)
  // ============================================================
  {
    number: 1,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `Alice and Ben have been together for three years. Ben just got home from a long day at work and is visibly tired. Alice has been wanting to talk about an upcoming trip they've been loosely planning — dates, budget, logistics. She brings it up over dinner. Ben sighs and says, "Can we not do this right now?" Alice feels dismissed because she's been waiting all day to have this conversation.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Let it go for tonight. Ben's tired and it's not urgent — she can bring it up this weekend when they're both relaxed.`,
      B: `Tell Ben that she understands he's tired, but explain that it's been on her mind all day and ask if they can talk for just ten minutes.`,
      C: `Tell Ben that his response was dismissive and that she deserves more than a sigh when she's trying to plan something for both of them.`,
      D: `Say "okay" but feel hurt, and probably be a little quiet for the rest of the evening.`,
    },
  },
  {
    number: 2,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `Ben forgot an important date — not a birthday or anniversary, but a dinner Alice had planned with her close friends that she'd told him about multiple times. When she gets upset, Ben says he's sorry but that he just has a lot going on at work and it honestly slipped his mind.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Accept the apology and move on. People forget things and it's not worth the fight.`,
      B: `Tell Ben she accepts his apology but explain that it's a pattern and she needs him to find a system to keep track of things that matter to her.`,
      C: `Tell Ben that saying he has a lot going on doesn't excuse it, because she has a lot going on too and still manages to remember what's important to him.`,
      D: `Tell him it's fine but honestly feel resentful, and bring it up again during the next unrelated disagreement.`,
    },
  },
  {
    number: 3,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `Alice and Ben are in the middle of a heated argument about finances. It's been going back and forth for twenty minutes and neither side is budging. Alice is getting emotionally overwhelmed and feels like she might say something she regrets.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Tell Ben she needs to pause this conversation and come back to it later when she's calmer.`,
      B: `Push through it because stopping now means it'll just hang over both of them unresolved.`,
      C: `Start crying and tell Ben that she can't handle how intense this is getting.`,
      D: `Concede on some points even if she doesn't fully agree, just to end the argument.`,
    },
  },
  {
    number: 4,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `After an argument the previous night, Ben wakes up acting completely normal — making coffee, chatting casually. Alice is still upset and feels like they never actually resolved anything. Ben's attitude feels like he's pretending it didn't happen.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Match his energy and move on. Maybe this is his way of extending an olive branch and she should meet him there.`,
      B: `Tell Ben that she appreciates him being warm this morning but that she still feels unresolved about last night and wants to revisit it briefly.`,
      C: `Be cold toward him until he notices and asks what's wrong, because he should know they didn't resolve things.`,
      D: `Bring it up directly and tell him that pretending nothing happened doesn't work for her and she needs closure before she can move forward.`,
    },
  },
  {
    number: 5,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `Alice comes home excited about a potential promotion at work. She starts telling Ben all about it, but she notices he seems distant and distracted. She asks what's wrong, and he says his mother just called with some difficult health news. Alice is torn between her own excitement and Ben's pain.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Set aside her news completely and focus entirely on Ben. Her promotion can wait — he needs her right now.`,
      B: `Acknowledge Ben's situation with genuine concern, spend time with him on it, but also share her news later that evening because both things matter.`,
      C: `Tell Ben she's really sorry about his mother, then ask if he'd like to hear some good news that might lift the mood.`,
      D: `Feel guilty about her excitement and downplay the promotion when she eventually mentions it, saying it's not a big deal.`,
    },
  },
  {
    number: 6,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Ben',
    situation: `Ben notices that Alice has been loading the dishwasher in a way he considers inefficient — plates facing the wrong direction, bowls stacked where they won't get clean. He decides to show her what he thinks is the correct method. Alice feels micromanaged and tells him it doesn't matter as long as the dishes get done.`,
    question: 'What would you tell Ben to do?',
    options: {
      A: `Let it go. Alice is right — if the dishes come out clean, the method doesn't matter. He's being controlling over something trivial.`,
      B: `Explain calmly why he thinks his way works better, but ultimately accept it if Alice doesn't want to change how she does it.`,
      C: `Stand his ground. If he's the one who notices the dishes aren't getting clean, she should be willing to adjust her approach.`,
      D: `Stop saying anything about it but just quietly re-do the dishwasher himself after she loads it.`,
    },
  },
  {
    number: 7,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Ben',
    situation: `Alice has had an incredibly stressful week — problems at work, a falling out with a friend, and she's been sleeping poorly. On Friday evening she breaks down crying on the couch. Ben isn't sure what to say or do. He feels overwhelmed by the intensity of her emotions and is worried about saying the wrong thing.`,
    question: 'What would you tell Ben to do?',
    options: {
      A: `Sit with her, hold her if she wants, and just be present without trying to fix anything. She doesn't need solutions right now.`,
      B: `Ask her what she needs — does she want to talk, does she want space, does she want a distraction? Let her guide it.`,
      C: `Try to cheer her up by suggesting they order her favorite food or watch something she loves. Shift the energy.`,
      D: `Give her some space to process. Go to another room for a bit and let her come to him when she's ready to talk.`,
    },
  },
  {
    number: 8,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `After a heated argument, Ben realizes he crossed a line and said something genuinely hurtful. He apologizes the next morning, saying he didn't mean it and he was just angry. Alice appreciates that he apologized but feels like his apology doesn't address the specific thing he said that hurt her — it feels generic rather than meaningful.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Tell Ben she appreciates the apology but explain specifically what hurt her and why, and ask him to acknowledge that part directly.`,
      B: `Accept the apology at face value. He said sorry, he clearly feels bad, and pushing for more might start another fight.`,
      C: `Tell Ben that a real apology means understanding what you did wrong, not just saying you didn't mean it, and that she needs him to reflect on why he said what he said.`,
      D: `Say she needs more time before she can accept the apology because she's still processing what he said and isn't ready to move past it.`,
    },
  },
  {
    number: 9,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `Alice has asked Ben multiple times to stop leaving his clothes on the bedroom floor. Each time he says he'll work on it, but nothing changes. When she brings it up again, Ben says, "That's just how I am. You knew that when we started dating. I feel like you're always trying to change me."`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Tell Ben that asking him to pick up his clothes isn't trying to change who he is as a person, and that small adjustments are part of sharing a life with someone.`,
      B: `Let it go and just accept it. It's clothes on the floor — not worth the recurring argument. She can pick them up or ignore them.`,
      C: `Tell Ben that "that's just how I am" isn't an acceptable excuse for repeatedly ignoring something she's asked for, and that she needs to see actual effort.`,
      D: `Ask Ben what things about her bother him, and suggest they each pick one habit to work on together so it feels mutual rather than one-sided.`,
    },
  },
  {
    number: 10,
    batch: 'romantic',
    batchLabel: 'Romantic Conflict',
    subject: 'Alice',
    situation: `Ben bought a new gaming console — a significant purchase — without mentioning it to Alice beforehand. When she sees the box, she asks about it. Ben says it was his money from his personal account and he shouldn't need permission to buy something for himself. Alice isn't upset about the console itself but about the fact that he didn't even mention he was thinking about it.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Explain to Ben that it's not about permission — it's about the courtesy of a heads-up when spending a significant amount, even from personal funds.`,
      B: `Let it go. If it's his personal money, he has a point. She wouldn't want him policing her personal purchases either.`,
      C: `Tell Ben that in a partnership, major purchases should be discussed regardless of whose account they come from, and suggest they set a threshold amount above which they always check in with each other.`,
      D: `Feel bothered but not say anything, then be more guarded about sharing her own financial decisions going forward.`,
    },
  },

  // ============================================================
  // BATCH 2 — DAILY LIFE & LOGISTICS (Scenarios 11–20)
  // ============================================================
  {
    number: 11,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'them',
    situation: `Alice and Ben need to decide where to spend the winter holidays. Alice wants to visit her parents, who she hasn't seen in months. Ben wants to stay home because he's had an exhausting year and the idea of traveling during the holidays feels overwhelming. They've gone back and forth twice and neither is budging.`,
    question: 'What would you tell them to do?',
    options: {
      A: `Alice should go visit her family alone, and Ben should stay home. They don't have to do everything together.`,
      B: `They should keep talking until they find a genuine compromise — maybe a shorter visit, or her parents come to them.`,
      C: `Ben should go with Alice. Family is important, and sometimes you show up for your partner even when it's not what you'd choose.`,
      D: `Alice should stay home this year. Ben is clearly burnt out, and pushing him to travel when he's exhausted isn't fair.`,
    },
  },
  {
    number: 12,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Alice',
    situation: `While Ben was away for a work trip, Alice reorganized the entire kitchen — new drawer assignments, rearranged cabinets, different shelf layouts. She's proud of how much more efficient it is. When Ben gets home, he can't find anything and is visibly frustrated. He says she should have waited to do it together.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Acknowledge that she should have involved him and offer to walk him through the new layout, adjusting anything that genuinely doesn't work.`,
      B: `Tell Ben to give it a week before judging. Change feels annoying at first, but the new system is objectively better.`,
      C: `Apologize for not waiting and offer to redo it together, incorporating both of their preferences.`,
      D: `Tell Ben that she lives in the kitchen more than he does and she organized it in the way that makes her daily life easier, which he should respect.`,
    },
  },
  {
    number: 13,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Alice',
    situation: `Ben is venting about a terrible day at work. He's been talking for nearly thirty minutes — going through every detail of a conflict with his manager. Alice has been listening patiently, but she also had a rough day and has things she wants to talk about too. She's starting to feel invisible in the conversation.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Keep listening. He clearly needs to get this out, and being a good partner means being there even when it's one-sided sometimes.`,
      B: `Wait for a natural pause and then say, "I hear you, that sounds really frustrating. I also had a tough day — can I share mine too?"`,
      C: `Gently interrupt and tell Ben she needs to talk about her day too, because the conversation has been one-sided for a while.`,
      D: `Start to disengage — shorter responses, checking her phone — hoping he'll pick up on the cue and ask how she's doing.`,
    },
  },
  {
    number: 14,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Alice',
    situation: `Alice accidentally scraped Ben's car while pulling into the garage. There's a noticeable scratch on the passenger side. When she tells Ben, he's clearly upset. Alice says it was an accident and that he's overreacting — it's just a car. Ben says the issue isn't just the scratch, it's that she's dismissing how he feels about it.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Recognize that Ben has a point. Even if it's just a car to her, it matters to him, and dismissing his reaction made it worse. She should apologize for both the scratch and for minimizing his feelings.`,
      B: `Hold her ground. It was an accident, she told him right away, and getting upset about a scratch on a car is an overreaction. She shouldn't have to apologize for his disproportionate response.`,
      C: `Apologize for the scratch and acknowledge she shouldn't have said he was overreacting, but also explain that his intensity made her defensive.`,
      D: `Offer to pay for the repair and leave it at that. The practical solution matters more than an extended emotional conversation about a scratch.`,
    },
  },
  {
    number: 15,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Alice',
    situation: `After a full weekend of socializing — brunch with friends Saturday, a dinner party Saturday night, and a family gathering Sunday — Alice tells Ben she wants Monday evening completely to herself. No conversation, no plans, just alone time to recharge. Ben is a little hurt because he feels like she's shutting him out. He says, "We barely had any time just us this weekend either."`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Stick to her boundary. She knows what she needs to recharge, and Ben should respect that without taking it personally.`,
      B: `Explain to Ben that needing alone time isn't about rejecting him — it's about coming back to him as a better version of herself. Then take the evening.`,
      C: `Compromise. Spend the first half of the evening together doing something low-key, then take the rest of the night for herself.`,
      D: `Give in and spend the evening with Ben. His feelings matter, and she can find alone time another day.`,
    },
  },
  {
    number: 16,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Alice',
    situation: `Ben has a habit of interrupting Alice mid-sentence. She's mentioned it to him before, and he's tried to work on it, but it keeps happening. Tonight at dinner with another couple, he cuts her off mid-story to add his own version of events. Alice feels embarrassed and frustrated.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Address it with Ben privately after dinner. Tell him it happened again and that being interrupted in front of friends is embarrassing.`,
      B: `Let it go this time. He's aware of the issue and is trying. Bringing it up every time will just make him feel like he can never get it right.`,
      C: `In the moment, calmly say, "I wasn't finished," and continue her story. Address the pattern later at home.`,
      D: `Tell Ben after dinner that if he can't stop interrupting her, she's going to start pointing it out in real time, even in front of others.`,
    },
  },
  {
    number: 17,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'them',
    situation: `Alice and Ben have been debating whether to rent or buy a home for months. Alice believes buying is the smart financial move and they should stretch their budget. Ben thinks renting gives them flexibility and doesn't want the pressure of a mortgage. Every time it comes up, the conversation goes in circles. Neither has moved from their original position.`,
    question: 'What would you tell them to do?',
    options: {
      A: `Sit down with a financial advisor together and let the numbers guide the decision rather than their opinions.`,
      B: `Alice should accept that Ben isn't ready and table the conversation for six months. Pushing someone into a mortgage they're uncomfortable with is a recipe for resentment.`,
      C: `Ben should recognize that Alice has done the research and has valid points. Sometimes one partner needs to trust the other's judgment even when it feels uncomfortable.`,
      D: `They should each write down their top three concerns and trade lists. Understanding the other person's fears might break the deadlock.`,
    },
  },
  {
    number: 18,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Alice',
    situation: `Alice picks up Ben's phone to check the time and sees a notification from a female coworker that reads, "Can't wait for tomorrow :)" Alice feels a jolt of jealousy. She knows Ben has a close female colleague he works on projects with, but the message feels overly familiar to her.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Ask Ben about it casually and without accusation — "I saw a message pop up from your coworker, what's happening tomorrow?" Trust his answer.`,
      B: `Say nothing. She knows Ben's coworker, she knows they work together, and reading anything into a friendly text says more about her insecurity than about Ben's behavior.`,
      C: `Tell Ben the message made her uncomfortable and ask him to be more aware of how his friendships with female colleagues might look from her perspective.`,
      D: `Keep it to herself but start paying closer attention to how Ben talks about this coworker going forward.`,
    },
  },
  {
    number: 19,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'Ben',
    situation: `Ben's close friend tells him that Alice was complaining about him at a group dinner last week — saying he doesn't help enough around the house and that she feels like his mother sometimes. Ben is hurt and embarrassed. When he brings it up, Alice says she was just venting to friends and didn't mean it as seriously as it sounds.`,
    question: 'What would you tell Ben to do?',
    options: {
      A: `Tell Alice that venting to friends about their relationship — especially in a way that paints him in a bad light — crossed a line, and he needs her to keep those conversations private.`,
      B: `Take a step back and consider whether what she said to her friends might actually be true. If she feels that way, maybe the real issue is the division of labor, not the venting.`,
      C: `Tell Alice he understands needing to vent but ask her to come to him first with those frustrations before taking them to other people.`,
      D: `Let it go. Everyone vents to friends. It's embarrassing but not worth a fight, and making a big deal of it might make her less open with him in the future.`,
    },
  },
  {
    number: 20,
    batch: 'daily',
    batchLabel: 'Daily Life & Logistics',
    subject: 'them',
    situation: `Alice and Ben were both supposed to book a hotel for their anniversary weekend trip. Each assumed the other had handled it. They arrive at their destination to discover neither booked anything, and everything nearby is sold out. They're standing in a parking lot, exhausted from the drive, and the blame game starts.`,
    question: 'What would you tell them to do?',
    options: {
      A: `Both should own it equally. Neither confirmed, neither followed up, so it's a shared failure. Focus energy on finding a solution instead of assigning blame.`,
      B: `Whoever originally suggested the trip should take more responsibility — the person who initiates should follow through on the details.`,
      C: `Alice should tell Ben exactly why she assumed he was handling it, and ask him to explain his assumption too. The miscommunication is the real problem to solve.`,
      D: `One of them should just apologize first — even if they don't feel fully at fault — to break the tension so they can start problem-solving.`,
    },
  },

  // ============================================================
  // BATCH 3 — SOCIAL & EXTERNAL (Scenarios 21–30)
  // ============================================================
  {
    number: 21,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Alice',
    situation: `Ben's mother calls several times a week and frequently makes passive-aggressive comments about Alice — her cooking, her career choices, how she keeps the house. Ben tends to stay quiet during these calls rather than pushing back. Alice has told him it bothers her, but he says, "That's just how my mom is," and doesn't want to create family drama.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Tell Ben that she understands he doesn't want conflict with his mother, but his silence feels like agreement, and she needs him to set at least one clear boundary.`,
      B: `Accept that this is Ben's relationship with his mother and find her own way to cope — limit her time on calls, leave the room, or develop thicker skin.`,
      C: `Start addressing Ben's mother directly herself, politely but firmly, since Ben won't do it.`,
      D: `Have a deeper conversation with Ben about how his mother's comments make her feel, focusing on her emotions rather than demanding he act.`,
    },
  },
  {
    number: 22,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Alice',
    situation: `Alice and Ben are at a mutual friend's party. Ben's ex-girlfriend is there unexpectedly. The ex approaches them, is friendly, and makes a lighthearted joke referencing something from when she and Ben dated. Ben laughs along. Alice forces a smile but feels a sting of jealousy and discomfort.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Mention it to Ben later, honestly. Say something like, "That interaction was a little uncomfortable for me. I'm not accusing you of anything, I just want you to know how I felt."`,
      B: `Let it go entirely. The ex was being friendly, Ben was being polite, and reading anything negative into a brief social interaction is unnecessary.`,
      C: `Tell Ben on the way home that she didn't appreciate him laughing at an inside joke with his ex in front of her, and that he should have been more aware of how it would make her feel.`,
      D: `Shrug it off in the moment but process it internally. If it keeps bothering her later, then bring it up.`,
    },
  },
  {
    number: 23,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Alice',
    situation: `Ben's best friend just went through a bad breakup and asks if he can stay at Ben and Alice's apartment for a few weeks while he gets back on his feet. Ben says yes immediately because his friend is hurting. Alice finds out after the fact and is upset — not because she doesn't want to help, but because Ben committed their shared space without asking her.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Tell Ben that she supports helping his friend, but he should have discussed it with her first since it's their shared home. Then set ground rules together.`,
      B: `Let it go this time because the friend is in crisis, but make it clear to Ben that any future decisions involving their shared space need to be made together.`,
      C: `Tell Ben that his friend can't stay. He made a unilateral decision about their home, and accepting it would set a precedent she's not comfortable with.`,
      D: `Accept it without saying anything. Ben's friend is hurting, and making this about her right now feels selfish.`,
    },
  },
  {
    number: 24,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Alice',
    situation: `Alice tells Ben about feedback she got from her boss — that she needs to be more assertive and speak up more in meetings. She's feeling vulnerable about it. Ben, trying to be supportive, says, "Honestly, I think your boss has a point. You do tend to hold back, even with me sometimes. Maybe this is a chance to grow."`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Thank Ben for his honesty, even though it stings. He's probably right, and hearing it from someone who knows her well might be more useful than hearing it from her boss alone.`,
      B: `Tell Ben that she wasn't asking for his assessment — she was sharing something that made her feel vulnerable, and his response felt like piling on rather than supporting.`,
      C: `Take some time to think about what he said. He might have a point, but she needs to sit with it before she can engage with the feedback constructively.`,
      D: `Tell Ben that there's a difference between being honest and being hurtful, and that the moment she's sharing an insecurity is not the time to confirm it.`,
    },
  },
  {
    number: 25,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'them',
    situation: `A close mutual friend is going through a painful divorce and has been leaning heavily on both Alice and Ben for support. Alice wants to be deeply involved — checking in daily, offering to help with logistics, being available whenever the friend needs to talk. Ben thinks they should be supportive but maintain some distance, because it's starting to take an emotional toll on both of them.`,
    question: 'What would you tell them to do?',
    options: {
      A: `Follow Alice's approach. When a friend is suffering, you show up fully. Setting boundaries with someone in crisis feels cold.`,
      B: `Follow Ben's approach. They can't pour from an empty cup, and getting too enmeshed in someone else's divorce could strain their own relationship.`,
      C: `Find a middle ground — check in regularly but set some limits on availability. Be honest with the friend that they care but also need to protect their own wellbeing.`,
      D: `Let each of them support the friend in their own way. Alice can be more involved, Ben can be more measured, and neither needs to match the other's approach.`,
    },
  },
  {
    number: 26,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Alice',
    situation: `Ben loses his job unexpectedly. Instead of telling Alice right away, he keeps it to himself for three days — spending his usual hours at a coffee shop, pretending to go to work. When Alice finds out, she's hurt that he hid it. Ben says he needed time to process it himself before bringing her into it, and he didn't want to worry her until he had a plan.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Tell Ben that she understands he was processing, but hiding something this significant made her feel excluded from his life. Partners share burdens — that's the whole point.`,
      B: `Respect that Ben needed space to process. Everyone handles shock differently, and three days isn't that long. Focus on supporting him now rather than making it about her feelings.`,
      C: `Tell Ben that the hiding is a bigger issue than the job loss. If he can conceal this, what else might he keep from her? She needs to be able to trust that he'll come to her with important things.`,
      D: `Acknowledge his need for space but explain that she felt blindsided, and ask him to promise that in the future he'll at least tell her something big is happening, even if he's not ready to discuss the details.`,
    },
  },
  {
    number: 27,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Alice',
    situation: `Alice's parents have always thought Ben lacks ambition. At a family dinner, her father makes a pointed comment: "So, Ben, any plans to move up at work, or are you happy where you are?" Alice knows her dad means it as a dig. Ben looks at her, expecting her to say something. Alice is torn between defending Ben and not starting a fight with her father.`,
    question: 'What would you tell Alice to do?',
    options: {
      A: `Redirect the conversation diplomatically without directly confronting her father — something like, "Ben is doing great, Dad. Let's talk about something else."`,
      B: `Address it directly. Tell her father that Ben's career is not up for discussion, and that comments like that are disrespectful.`,
      C: `Stay quiet in the moment to avoid a scene, but talk to her father privately afterward and tell him those comments need to stop.`,
      D: `Talk to Ben after dinner and be honest that she partially agrees with her father but didn't know how to handle the moment, and ask how they can work on this together.`,
    },
  },
  {
    number: 28,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'them',
    situation: `Alice and Ben are having dinner with close friends when the conversation turns to parenting philosophies. Alice shares her views on structured routines for children; Ben disagrees and argues for a more relaxed approach. The discussion gets heated, and their friends start looking uncomfortable. After the friends leave, the tension between Alice and Ben lingers.`,
    question: 'What would you tell them to do?',
    options: {
      A: `Table it for now. They don't even have kids yet, and arguing about hypothetical parenting in front of friends was unnecessary. Come back to it when it's actually relevant.`,
      B: `Talk it through tonight while it's fresh. The disagreement revealed something real about their different values, and pretending it didn't happen won't help.`,
      C: `Acknowledge that they both got carried away in front of friends, and agree that future disagreements like this should happen privately rather than at dinner parties.`,
      D: `Each take a day to think about why they reacted so strongly, then come back and discuss what the real underlying concern is — it's probably not actually about bedtime routines.`,
    },
  },
  {
    number: 29,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'them',
    situation: `Ben's coworker invites him and Alice to a dinner party. Alice doesn't want to go — she finds the coworker pretentious and the events draining. Ben says it's important for his work relationships and asks Alice to make the effort for his sake. Alice says she shouldn't have to spend her free time with people she doesn't enjoy.`,
    question: 'What would you tell them to do?',
    options: {
      A: `Alice should go. Supporting your partner's professional relationships is part of being a team, even when it's not fun. She can set a time limit so she has an out.`,
      B: `Ben should go alone. Alice shouldn't be forced to socialize with people she doesn't like, and Ben is capable of attending a dinner party by himself.`,
      C: `They should compromise — Alice goes to this one, but Ben agrees not to make it a regular expectation. Trade-offs work both ways.`,
      D: `Alice should tell Ben exactly why she doesn't want to go, and Ben should listen without dismissing her reasons. The decision should come after they've actually heard each other.`,
    },
  },
  {
    number: 30,
    batch: 'social',
    batchLabel: 'Social & External',
    subject: 'Ben',
    situation: `Alice suggests that she and Ben try couples therapy — not because anything is terribly wrong, but because she thinks it could strengthen their communication and prevent small issues from becoming big ones. Ben resists. He says their relationship is fine, that therapy is for people with real problems, and that he'd feel uncomfortable talking to a stranger about their private life.`,
    question: 'What would you tell Ben to do?',
    options: {
      A: `Try it. Alice is asking for something that could benefit both of them, and resisting because of stigma or discomfort means prioritizing his ego over the relationship.`,
      B: `Be honest about why it makes him uncomfortable. If it's about vulnerability or stigma, say that — don't just dismiss the idea. Then work together to find a version he could try.`,
      C: `Suggest an alternative. If therapy feels too formal, maybe they try a couples workshop, read a relationship book together, or set aside weekly time to check in with each other.`,
      D: `Hold his boundary. If he genuinely doesn't think they need it, he shouldn't be pressured into it. Alice should respect that he's not ready.`,
    },
  },
]
